### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by rubenrubiob** [raviqqe/gherkin2markdown#4]
Hi,

I am trying to install gherking2markdown but I am getting an error:

```bash
$ go get -u github.com/raviqqe/gherkin2markdown
package github.com/cucumber/cucumber/cucumber-messages/go/v3: cannot find package "github.com/cucumber/cucumber/cucumber-messages/go/v3" in any of:
	/usr/local/go/src/github.com/cucumber/cucumber/cucumber-messages/go/v3 (from $GOROOT)
	/Users/rubio/go/src/github.com/cucumber/cucumber/cucumber-messages/go/v3 (from $GOPATH)
```

Am I missing something? My Go version is:

```bash
$ go version
go version go1.12.7 darwin/amd64
```

I am not proficient in Go, so, if you need more information, jsut let me know!

Thank you!

Regards.

**Comment by raviqqe** [comment]
Can you try `GO111MODULE=on go get -u github.com/raviqqe/gherkin2markdown`?

**Comment by rubenrubiob** [comment]
Thank you, it works perfectly!

Is that something that I missed or something that should be in the docs?

**Comment by raviqqe** [comment]
Go modules is going to be enabled by default in the future release of Go. For now, we need to enable it manually... https://blog.golang.org/using-go-modules
