### ISSUE TITLE
Template parameters are not encoded correctly into markdown

### ISSUE THREAD

**Issue by cakoolen** [raviqqe/gherkin2markdown#56]
Whenever we use a scenario outline with template parameters the markdown generated from it is interpreted as a non-existent HTML tag because the `<>` characters are not escaped. Would it be possible to escape at least the leading bracket `\<` such that the parameter is not interpreted as html anymore?

**Comment by raviqqe** [comment]
Yeah, I think we can. Is it possible for you to share the Markdown renderer you use? For example, GitHub's works correctly even with template parameters as shown in the readme.

**Comment by cakoolen** [comment]
We use mkdocs to generate html from the markdown.

Currently it only runs with the following extensions:
```
markdown_extensions:
  - codehilite
  - plantuml_markdown
```
That in turn uses the python markdown implementation: https://python-markdown.github.io/

The biggest issue is of course: does this break any existing use-case.

**Comment by raviqqe** [comment]
Closed by #57 and #58.
