### ISSUE TITLE
unable to go get this package (+ a workaround)

### ISSUE THREAD

**Issue by paulkarayan** [raviqqe/gherkin2markdown#6]
I was unable to install this package on mac osx. got this error
> ➜  demo-ecommerce-docs git:(master) ✗ go get -u github.com/raviqqe/gherkin2markdown       
> package github.com/cucumber/cucumber-messages-go/v3: cannot find package "github.com/cucumber/cucumber-messages-go/v3" in any of:
>         /usr/local/opt/go/libexec/src/github.com/cucumber/cucumber-messages-go/v3 (from $GOROOT)
>         /Users/paulkarayan/go-wks/src/github.com/cucumber/cucumber-messages-go/v3 (from $GOPATH)
> [1]    54929 exit 1     go get -u github.com/raviqqe/gherkin2markdown

here's my workaround (per https://stackoverflow.com/questions/30188499/how-to-do-go-get-on-a-specific-tag-of-a-github-repository Gregory Russell)
- go get the cucumber-messages-go package
- git checkout <commit with v3>
- git checkout <commit with v5>
- go get github.com/raviqqe/gherkin2markdown 

those cucumber message commits are:
b2c070a0abb588b657d220a5b23b86284a3657a3
65104befcc1c9aa08bdb5ad957455089865f4e79

seems to work now. it looks like the /v3 no longer is how cucumber-messages-go works...

**Comment by raviqqe** [comment]
Fixed on master! Thanks for reporting the issue!
